"""add shelf_location to books

Revision ID: 2cafe4652a6b
Revises: dff5c6acd917
Create Date: 2026-05-25 00:56:55.039854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cafe4652a6b'
down_revision: Union[str, None] = 'dff5c6acd917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('shelf_location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'shelf_location')
    # ### end Alembic commands ###
